spring.application.name: togo
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
  liquibase:
    change-log: classpath:/liquidbase.master.xml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          auth-client:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            provider: vaulty-auth
        provider:
          vaulty-auth:
            token-uri: https://togoauth.kbanbah.com/auth/api/token
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: auth-client

vaulty:
  auth.url: https://togoauth.kbanbah.com/auth
  client.id: ${CLIENT_ID}
  scopes: api.share.app

server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: ${user.home}/logs/togo/tomcat
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd
      rotate: true
      rename-on-rotate: false
      max-days: 10
      pattern: '%{yyyy-MM-dd HH:mm:ss.SSS}t %a "%m %U%q %H" %s %b %Dms'
