spring:
  datasource:
    url: jdbc:h2:mem:local;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
