---
- name: Deploy to UAT
  hosts: uat
  become: false

  tasks:
    - name: Copy stop.sh to server
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../.github/scripts/stop.sh"
        dest: ~/togo/stop.sh
        mode: '0755'

    - name: Copy start.sh to server
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../.github/scripts/start.sh"
        dest: ~/togo/start.sh
        mode: '0755'

    - name: Stop application
      ansible.builtin.shell: ~/togo/stop.sh
      ignore_errors: true

    - name: Copy jar to server
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../build/libs/share_api-0.0.1.jar"
        dest: ~/togo/share_api-0.0.1.jar
        mode: '0755'

    - name: Start application
      ansible.builtin.shell: ~/togo/start.sh
      args:
        chdir: ~/togo
