name: Deploy to UAT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Give gradle permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/share_api-0.0.1.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: cytopia/ansible:latest-tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs/

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UAT_SSH_KEY }}" > ~/.ssh/uat_key
          chmod 600 ~/.ssh/uat_key

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible/inventory/uat ansible/deploy.yml
